[[Languages.en.menu.switchlang]]
  name = "Deutsch"
  identifier = ""
  weight = 4
  url = "de"

[[Languages.en.menu.switchlang]]
  name = "Esperanto"
  identifier = ""
  weight = 4
  url = "eo"

[[Languages.en.menu.switchlang]]
  name = "Français"
  identifier = ""
  weight = 4
  url = "fr"

[[Languages.en.menu.switchlang]]
  name = "Nederlands"
  identifier = ""
  weight = 4
  url = "nl"

[[Languages.en.menu.switchlang]]
  name = "Język polski"
  identifier = ""
  weight = 4
  url = "pl"

[[Languages.en.menu.switchlang]]
  name = "繁體中文"
  identifier = ""
  weight = 4
  url = "zh-hant-tw"

[Languages.en]
languageCode = "en"
title = "JoinPeerTube"
weight = 1

[[Languages.en.menu.main]]
name = "FAQ"
identifier = "faq"
weight = 2
title = "FAQ"
url = "/en/faq/"

[[Languages.en.menu.main]]
name = "Support"
weight = 3
identifier = ""
url = "https://framacolibri.org/c/peertube"

[[Languages.en.menu.main]]
name = "Documentation"
weight = 4
identifier = ""
url = "https://docs.joinpeertube.org/"

[[Languages.en.menu.main]]
name = "Source code"
weight = 5
identifier = ""
url = "https://github.com/Chocobozzz/PeerTube"

[[Languages.en.menu.main]]
name = "Instances"
weight = 6
identifier = ""
url = "https://instances.joinpeertube.org"

[[Languages.en.menu.main]]
name = "Hall of fame"
identifier = "hof"
weight = 7
title = "Hall of fame"
url = "/en/hall-of-fame/"